apiVersion: v1
kind: Namespace
metadata:
  name: mirai
  labels:
    # Pod Security Standards - restricted is most secure
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
    # Tenant identification
    tenant: mirai
    environment: production
