apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-static-sites
  namespace: argocd
  labels:
    env: prod
    domain: standalone
    tier: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab-apps
  source:
    repoURL: https://github.com/sojohnnysaid/static-sites.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: static-sites
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
